controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
categoria:
    path: /categoria
    controller: App\Controller\CategoriaController::index
produto:
    path: /produto
    controller: App\Controller\ProdutoController::index
